GET http://localhost:3000/

### GET - Listar todos os usuários
GET http://localhost:3000/usuarios
Content-Type: application/json


### GET - Buscar um usuário por ID
GET http://localhost:3000/usuarios/1
Content-Type: application/json


### POST - Criar um novo usuário
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nome": "Jeniffer Soares",
  "email": "jeniffer.soares@gmail.com",
  "senha_hash": "1234"
}


### PUT - Atualizar um usuário
PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
  "nome": "Jeniffer Soares",
  "email": "jeniffer.soares@gmail.com",
  "senha_hash": "j@1505"
}


### DELETE - Excluir um usuário
DELETE http://localhost:3000/usuarios/1
Content-Type: application/json

### GET - Listar todos os eventos
GET http://localhost:3000/eventos
Content-Type: application/json


### GET - Buscar um evento por ID
GET http://localhost:3000/eventos/1
Content-Type: application/json


### POST - Criar um novo evento
POST http://localhost:3000/eventos
Content-Type: application/json

{
  "nome": "Semana da Tecnologia",
  "descricao": "Evento com palestras e workshops sobre inovação.",
  "data": "2025-06-20",
  "local": "Auditório Principal",
  "duracao_horas": 5,
  "entidade_id": 1
}


### PUT - Atualizar um evento
PUT http://localhost:3000/eventos/1
Content-Type: application/json

{
  "nome": "Semana da Tecnologia 2025",
  "descricao": "Evento com palestras atualizadas sobre tecnologia.",
  "data": "2025-06-21",
  "local": "Novo Auditório",
  "duracao_horas": 6,
  "entidade_id": 1
}


### DELETE - Excluir um evento
DELETE http://localhost:3000/eventos/1
Content-Type: application/json
